name: HiverRadeem
main: me\frogas\hiverradeem\HiverRadeem
api: 
- 2.0.0
- 3.0.0
- 4.0.0
- 5.0.0
version: 1.0
author: Frogas

commands:
  hiverradeem:
    description: "Radeem your code for get reward."
